global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/apployd-recording-rules.yml
  - /etc/prometheus/rules/apployd-alerts.yml

scrape_configs:
  - job_name: 'apployd-control-plane'
    metrics_path: /metrics
    static_configs:
      - targets: ['control-plane:4000']

  - job_name: 'apployd-deployment-engine'
    metrics_path: /metrics
    static_configs:
      - targets: ['deployment-engine:9102']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor:8080']
